#!/bin/bash
set -o errtrace 
# set -o nounset
trap onexit 1 2 3 15 ERR

r=( $(openssl rand 100000 | sha1sum) )
database_name="${r:0:8}"

function onexit() {
    local exit_status=${1:-$?}
    echo Exiting $0 with $exit_status
    if [ ! -z "${xvfb_status}" ]; then
      /etc/init.d/xvfb stop
    fi
    destroy_test_database ${database_name}
    exit $exit_status
}

configure_test_database ${database_name}

if [ -d "./spec/dummy/config" ]; then
  echo " . preparing database.yml"

  DATABASE_CONFIGURATION=$(cat <<EOF
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ${database_name}_test
  pool: 5
  username: ${database_name}_test
  password: ${database_name}_test
  socket: /var/run/mysqld/mysqld.sock
EOF
  )

  echo "${DATABASE_CONFIGURATION}" > "./spec/dummy/config/database.yml"
fi

bundle install --path vendor/gems --binstubs
RAILS_ENV=test bundle exec rake db:setup
/etc/init.d/xvfb start
xvfb_status=1
export DISPLAY=:99 firefox
RAILS_ENV=test bundle exec rspec spec

onexit
